name: Cross-Compile for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ 2. Instalação das dependências (compilação cruzada)
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            mingw-w64 \
            liblua5.1-0-dev \
            libboost-all-dev \
            libxml2-dev \
            zlib1g-dev \
            cmake \
            make \
            git

      # ✅ 3. Compilar com MinGW
      - name: Build with MinGW
        run: |
          cd Source
          make \
            CC=x86_64-w64-mingw32-gcc \
            CXX=x86_64-w64-mingw32-g++ \
            -j$(nproc)

      # ✅ 4. Fazer upload do binário gerado (.exe)
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: otserv-windows-exe
          path: Source/*.exe
