name: Cross-Compile for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          mingw-w64 \
          liblua5.1-0-dev \
          libboost-all-dev \
          libxml2-dev \
          zlib1g-dev \
          cmake \
          make \
          git

    - name: Build with MinGW (cross-compile)
      run: |
        cd Source
        make CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ -j$(nproc)

    - name: List generated .exe files
      run: ls -lh Source/*.exe || echo "Nenhum executável encontrado."

    - name: Compress .exe into zip
      run: |
        cd Source
        zip otserv-windows.zip *.exe

    - name: Upload Windows executable ZIP
      uses: actions/upload-artifact@v3.1.2
      with:
        name: otserv-windows-zip
        path: Source/otserv-windows.zip
